# Generated by Django 4.0.3 on 2022-03-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=10)),
                ('dataNascimento', models.DateField()),
            ],
        ),
    ]
